SELECT NOME,
CASE
	WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'Velho'
    WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <= 1995 THEN 'Jovem'
    ELSE 'Criança'
END AS Classificação
FROM tabela_de_clientes;
