CREATE TABLE CLIENTES
(CPF VARCHAR(11) PRIMARY KEY,
Nome VARCHAR(100) NOT NULL,
Endereço VARCHAR(150) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
Cidade VARCHAR(50) NOT NULL,
Estado VARCHAR(50) NOT NULL,
CEP VARCHAR(8) NOT NULL,
`Data Nascimento` DATE NOT NULL,
Idade INT NOT NULL,
Sexo VARCHAR(1) NOT NULL,
`Limite Crédito` FLOAT NOT NULL,
`Volume Compra` FLOAT NOT NULL,
`Primeira Compra` BOOLEAN NOT NULL
);
