ALTER TABLE NOTAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE NOTAS ADD CONSTRAINT FK_ITENS_NOTAS
FOREIGN KEY (NUMERO) REFERENCES ITENS_NOTAS (NUMERO);

ALTER TABLE NOTAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (`CODIGO_DO_PRODUTO`) REFERENCES PRODUTOS (`CODIGO_DO_PRODUTO`);
