DELIMITER $$
CREATE PROCEDURE sp_Exerc01 ()
BEGIN
DECLARE Cliente VARCHAR(10) DEFAULT "João";
DECLARE Idade INTEGER DEFAULT 10;
DECLARE DataNascimento DATE DEFAULT "2007-01-01";
DECLARE Custo DECIMAL(4, 2) DEFAULT 10.23;
SELECT Cliente, Idade, DataNascimento, Custo;
END $$
DELIMITER ;

call sp_Exerc01;
