DELIMITER $$
CREATE PROCEDURE sp_qntd_notas_por_dia ( vDataInicial DATE, vDataFinal DATE)
BEGIN
DROP TABLE NOTAS_POR_DIA;
CREATE TABLE NOTAS_POR_DIA (DATA_NOTA DATE, QUANTIDADE INT);
WHILE vDataInicial <= vDataFinal
DO
INSERT INTO NOTAS_POR_DIA (DATA_NOTA, QUANTIDADE) VALUES (vDataInicial, (SELECT COUNT(*) FROM NOTAS
GROUP BY DATA_VENDA HAVING DATA_VENDA = vDataInicial));
SET vDataInicial = ADDDATE(vDataInicial, INTERVAL 1 DAY);
END WHILE;
SELECT * FROM NOTAS_POR_DIA;
END $$
DELIMITER ;

CALL sp_qntd_notas_por_dia ("2017-01-01", "2017-01-20");
