DELIMITER $$
CREATE PROCEDURE Quantidade_Notas (p_data DATE)
BEGIN
DECLARE NUMNOTAS INT;
SELECT COUNT(*) INTO NUMNOTAS FROM NOTAS
WHERE DATA_VENDA = p_data;
SELECT NUMNOTAS;
END $$
DELIMITER ;

CALL Quantidade_Notas ("2017-01-01");
