CREATE TABLE TABELA_ALEATORIOS(NUMERO INT);

DELIMITER $$
CREATE PROCEDURE sp_Tabela_Numeros (vQuantity INT)
BEGIN
DECLARE vCounter INT DEFAULT 0;
DELETE FROM TABELA_ALEATORIOS;
WHILE vCounter <= vQuantity
DO
INSERT INTO TABELA_ALEATORIOS(NUMERO) VALUES(f_numero_aleatorio(0, 1000));
SET vCounter = vCounter + 1;
END WHILE;
SELECT * FROM TABELA_ALEATORIOS;
END $$
DELIMITER ;

CALL sp_Tabela_Numeros (99);
